---
output: github_document
title:  Showing how to generate cases and staff numbers
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

The first step (after installing the package) is to load the library `epicaser`

```{r,echo=T,message=FALSE}
library(epicaser)
library(ggplot2)
library(dplyr)
```


Use the function `generate_epi_cases()` to generate synthetic data, so that we can test the model.

```{r,echo=T}
cases <- generate_epi_cases(staff_per_100K = 1200,
                               staff_recovery_delay = 6,
                               staff_absenteeism = 0.03)
cases
```

Plot the cases

```{r}
ggplot(cases,aes(x=Date,y=Cases))+
  geom_line()+
  geom_point()+
  scale_x_date(date_breaks = "1 week", minor_breaks = "1 day",date_labels="%b %e")+
  ggtitle("Cases")
```

Plot the staff numbers. These are Poisson random variables with the mean taken from the ODE model.
```{r}

ggplot(cases,aes(x=Date,y=cases$AvailableStaff))+
  geom_line()+
  geom_point()+
  scale_x_date(date_breaks = "1 week", minor_breaks = "1 day",date_labels="%b %e")+
  ggtitle("Available Staff")
```
